version: '3.4'

services:
  locattle:
    build:
      context: ./app
      args:
        UID: $(id -u)
    environment:
      - LANG=es_CO.UTF-8
      - DJANGO_ENV=$ENV
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      ./app:/code
      - static_volume:/code/staticfiles
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - locattle
    volumes:
      - static_volume:/code/staticfiles
volumes:
    static_volume:
