version: '3.4'

services:
  locattle:
    build:
      context: ./app
      args:
        - UID
    environment:
      - LANG=es_CO.UTF-8
      - DJANGO_ENV=$ENV
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./app:/code
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - locattle
    volumes:
      - ./app/staticfiles:/static
